use_cdn: false


navbar:
  logo: # choose [img] or [icon + title]
    img: '' #https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-NavBar@3x.png
    icon:
    title: '燃烧的浅蓝 <sup style="color:#ff9800">Blue</sup>'
  menu:
    - name: 主页
      icon: fad fa-book faa-tada
      url: /
      target: _self

    - name: 示例
      icon: fad fa-play-circle faa-tada
      url: /examples/

    - name: 帮助
      icon: fad fa-question-circle faa-tada
      url: /faqs/

    - name: 鸣谢
      icon: fad fa-heart
      url: /contributors/

    - name: 更多
      icon: fad fa-ellipsis-v
      rows:
        - name: 暗黑模式
          icon: fas fa-moon
          toggle: darkmode
        - name: 背景音乐
          icon: fas fa-compact-disc
        - name: hr
        - name: 本站源码
          url: https://github.com/volantis-x/volantis-docs/
        - name: 主题源码
          url: https://github.com/volantis-x/hexo-theme-volantis/
        - name: hr
        - name: 更新日志
          url: https://github.com/volantis-x/hexo-theme-volantis/releases/
        - name: 博客文章
          url: /archives/
        - name: hr
        - name: 旧版文档 v4
          url: /v4/getting-started/
        - name: 旧版文档 v3
          url: /v3/getting-started/
        - name: 旧版文档 v2
          url: /v2/getting-started/
  search: 搜索



cover:
  # height_scheme: full # full, half
  title: '燃烧的浅蓝'
  subtitle: '所有晦暗都留给过往，从此凛冬散尽，星河长明。'
  height_scheme: full # half
  background: # https://bing.ioliu.cn/v1/rand?w=1920&h=1200
  features:
    - name: 博客
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4f0.svg
      url: /
    - name: 文档
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f516.svg
      url: /v5/getting-started/
      target: _self
    - name: 示例
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4af.svg
      url: /examples/
    - name: 帮助
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4ac.svg
      url: /faqs/
    - name: 鸣谢
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f497.svg
      url: /contributors/
    - name: 归档
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f5c3.svg
      url: /archives/
    - name: 源码
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f9ec.svg
      url: https://github.com/volantis-x/hexo-theme-volantis/
      target: _self

article:
  preview:
    scheme: landscape # landscape
    # pin icon for post
    pin_icon: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4cc.svg
    # auto generate title if not exist
    auto_title: true # false, true
    # auto generate excerpt if not exist
    auto_excerpt: true # false, true
    # show split line or not
    line_style: solid # hidden, solid, dashed, dotted
    # show readmore button
    readmore: auto # auto, always
  # 文章详情页面的文章卡片本体布局方案
  body:
    top_meta: [author, category, date, counter]
    footer_widget:
      # ----------------
      # 参考资料、相关资料等 (for layout: post/docs)
      references:
        title: 参考资料
        icon: fas fa-quote-left
        # 在 front-matter 中:
        #   references:
        #     - title: 某篇文章
        #       url: https://
        # 即可显示此组件。
      # ----------------
      # 版权声明组件 (for layout: post/docs)
      copyright:
        enable: True
        # permalink: '本文永久链接是：'
        content:
          - '转载请标明出处！如果你觉得还不错，打个赏吧~'
        #  - permalink
      donate:
        enable: true
        images:
          - https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/qrcode/github@volantis.png
          - https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/qrcode/github@volantis.png
    meta_library:
      author:
        avatar: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/apple-touch-icon.png
        name: Volantis Team
        url: https://github.com/volantis-x/
      updated:
        title: '本页文档最后更新于：'



comments:
  service: valine
  valine:
    # js: https://cdn.jsdelivr.net/npm/valine@1.4/dist/Valine.min.js
    path: # 全局评论地址 目前设置全局评论地址后visitor失效,这是valine的问题
    placeholder: 快来评论吧~  # 评论占位提示
    # 其他配置项按照yml格式继续填写即可 除了 [el path placeholder emojiCDN emojiMaps] 选项
    appId: I9Gjg293pcHlVymgNfk9BD00-gzGzoHsz # your appId
    appKey: S1bpuzdnryigyp2rBdzevqLP  # your appKey

sidebar:
  # 主页、分类、归档等独立页面
  for_page: [guide, category, tagcloud, webinfo]
  # layout: docs/post 这类文章页面
  for_post: [toc]
  # 侧边栏组件库
  widget_library:
    guide:
      class: grid
      display: [ desktop, mobile ] # [desktop, mobile]
      header:
        icon: fas fa-map-signs
        title: 分类导航
      fixed: true # 固定宽度
      rows:
        - name: 常见问题
          icon: fas fa-question-circle
          url: /faqs/
        - name: 示例博客
          icon: fas fa-play-circle
          url: /examples/
        - name: 特别感谢
          icon: fas fa-handshake
          url: /contributors/
        - name: 测试博文
          icon: fas fa-file-alt
          url: /archives/
        - name: 主题源码
          icon: fas fa-file-code
          url: https://github.com/volantis-x/hexo-theme-volantis/
          rel: external nofollow noopener noreferrer
          target: _blank
        - name: 更新日志
          icon: fas fa-tags
          url: https://github.com/volantis-x/hexo-theme-volantis/releases/
          rel: external nofollow noopener noreferrer
          target: _blank
    # ---------------------------------------
    # blogger info widget
    blogger:
      class: blogger
      display: [desktop, mobile] # [desktop, mobile]
      avatar: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-NavBar@3x.png
      shape: rectangle # circle, rectangle
      url: /about/
      title:
      subtitle:
      jinrishici: true # Poetry Today. You can set a string, and it will be displayed when loading fails.
      social: true
    # ---------------------------------------
    # toc widget (valid only in articles)
    toc:
      class: toc
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fas fa-list
        title: 本文目录
      list_number: false
      min_depth: 2
      max_depth: 5
    # ---------------------------------------
    # category widget
    category:
      class: category
      display: [desktop] # [desktop, mobile]
      header:
        icon: fas fa-folder-open
        title: 文章
        url: /blog/categories/
    # ---------------------------------------
    # tagcloud widget
    tagcloud:
      class: tagcloud
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fas fa-tags
        title: 热门标签
        url: /blog/tags/
      min_font: 14
      max_font: 24
      color: true
      start_color: '#999'
      end_color: '#555'
    # ---------------------------------------
    # music widget
    music:
      class: music
      display: [ desktop, mobile ] # [desktop, mobile]
      pjaxReload: false

    # ---------------------------------------
    # qrcode widget
    donate:
      class: qrcode
      display: [desktop, mobile] # [desktop, mobile]
      height: 64px  # Automatic height if not set
      images:
        - https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/qrcode/github@volantis.png
        - https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/qrcode/github@volantis.png
    # ---------------------------------------
    # webinfo widget
    webinfo:
      class: webinfo
      display: [desktop]
      header:
        icon: fas fa-award
        title: 站点信息
      type:
        article:
          enable: true
          text: '文章数目：'
          unit: '篇'
        runtime:
          enable: true
          data: '2020/01/01'    # 填写建站日期
          text: '已运行时间：'
          unit: '天'
        wordcount:
          enable: true
          text: '本站总字数：'   # 需要启用 wordcount
          unit: '字'
        siteuv:
          enable: true
          text: '本站访客数：'   # 需要启用 busuanzi
          unit: '人'
        sitepv:
          enable: true
          text: '本站总访问量：' # 需要启用 busuanzi
          unit: '次'
        lastupd:
          enable: true
          friendlyShow: true    # 更友好的时间显示
          text: '最后活动时间：'
          unit: '日'
    help:
      class: page
      display: [desktop, mobile]
      header:
        icon: fas fa-headset
        title: 帮助
      pid: faq
      content: excerpt # excerpt, more, content

    news:
      class: list
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fas fa-exclamation-triangle
        title: 近期公告
      rows:
        - name: 关于主题与文档的更新
          icon: fas fa-info-circle
          url: https://github.com/volantis-x/hexo-theme-volantis/issues/215
        - name: 升级小助手
          icon: fas fa-angle-double-up
          url: /v3/getting-started/#升级小助手


site_footer:
  layout: [aplayer, social]
  # layout: [aplayer, social, source, analytics, copyright]
  copyright: '[Copyright © 2017-2021 Volantis Team](https://github.com/volantis-x/)'
  social:
    - img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org@1.1/icon/1322024-social-media/020-rss.svg
      url: atom.xml
    - img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org@1.1/icon/1322024-social-media/029-github.svg
      url: https://github.com/volantis-x/
    - img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org@1.1/icon/1322024-social-media/010-facebook.svg
      url: /
    - img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org@1.1/icon/1322024-social-media/018-twitter.svg
      url: /
    - img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org@1.1/icon/1322024-social-media/045-telegram.svg
      url: /
    - img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org@1.1/icon/1322024-social-media/006-youtube.svg
      url: /


tag_plugins:
  # {% note text %}
  note: # style for default note:
    iconfont: 'Font Awesome 5 Pro'

plugins:
  clipboard:
    enable: true
  fontawesome: https://cdn.jsdelivr.net/gh/inkss/fontawesome@5.15.3/css/all.min.css
  parallax:
    enable: true
    position: cover       # cover: sticky on the cover.   fixed: Fixed as background for the site.
    shuffle: true         # shuffle playlist
    duration: 10000       # Duration (ms)
    fade: 1500            # fade duration (ms) (Not more than 1500)
  aplayer:
    enable: true
    autoplay: false
    volume: 0.4
    order: random
    # id: 4917530132 # vol red
    # id: 4917524698 # vol blue
    # id: 76244489 # vol white
    # id: 5135845906 # for Volantis 3.0
    id: 5062959861 # TOP 30

  message:          # 音乐通知，播放、暂停、失败 时的图标
    enable: true
    icon:     # 默认图标，支持对图标添加颜色，可选值：see：/source/css/_plugins/message.styl
      default: fal fa-info-circle light-blue
      quection: fal fa-question-circle light-blue
    copyright:  # 是否在复制时弹出版权提示
      enable: ture
      title: '知识共享许可协议'
      message: '转载请著名作者和出处：燃烧的浅蓝。'
      icon: 'fab fa-creative-commons light-blue'
    aplayer:
      enable: true
      play: fal fa-play light-blue
      pause: fal fa-pause light-blue
      error: fal fa-exclamation-square red
  darkmode:
    enable: true
  gitter:
    room: hexo-theme-volantis/community

analytics:
  busuanzi: #https://cdn.jsdelivr.net/gh/volantis-x/cdn-busuanzi@2.3/js/busuanzi.pure.mini.js
  leancloud:
    app_id: GCYDRKI6XRkyC7EuEhJv90ia-MdYXbMMI
    app_key: 4xKBXGBj6BgecU62vff5rJHs
    custom_api_server: # 一般不需要写，除非自定义了 API Server

custom_css:
  navbar:
    height: 64px
    effect: [blur] # [shadow, floatable, blur]
  cursor:
    enable: true
  font_smoothing: true
  sidebar:
    effect: [blur] # [shadow, floatable, blur]
  body:
    effect: [blur] # [shadow, floatable, blur]
  scrollbar:
    size: 8px
    border: 4px
    color: '#2196f3'
    hover: '#ff5722'
  fontfamily:
    logofont:
      fontfamily: 'Dosis, "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
      name: 'Dosis'
      url: https://cdn.jsdelivr.net/gh/volantis-x/cdn-fonts@20.5.30/Dosis/Dosis-Medium.ttf
      weight: normal
      style: normal
    bodyfont:
      fontfamily: 'Dosis, "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
      name: 'Dosis'
      url: https://cdn.jsdelivr.net/gh/volantis-x/cdn-fonts@20.5.30/Dosis/Dosis-Medium.ttf
      weight: normal
      style: normal

rightmenu:
  enable: true
  faicon: fad PETERRIVE
  print:
    icon: fad fa-print TURQUOISE
  darkmode:
    icon: fad fa-eclipse-alt WISTERIA
  reading:
    icon: fad fa-book-open EMERALD
  help:
    icon: fad fa-question EMERALD
  examples:
    icon: fad fa-rss PETERRIVE
  contributors:
    icon: fad fa-fan fa-spin AMETHYST
  source_docs:
    icon: fad fa-code-branch WETASPHALT
  source_theme:
    icon: fad fa-file-code CONCRETE